### ISSUE TITLE
Neutral: Footnote 1

### ISSUE THREAD

**Issue by misterperson** [t7leeschool/t7leeschool.github.io#13]
Yoshimitsu ws1+2 is also an i10 mid when hitting deep. I think this is a generic ws move, but Lee's version is i12-13; not sure if anyone else has this tool as an i10.

**Comment by twaritwaikar** [comment]
Thanks for noting. We will probably just list ws3,3 as "one of the fastest mids in the game". Doesn't really make sense to list all contending moves in the footnotes. Also, the footnote is pretty useless too.
