### ISSUE TITLE
Should beginner BNBs use f~N ws2,4 - or skip b+2,4,3

### ISSUE THREAD

**Issue by RogerDodger** [t7leeschool/t7leeschool.github.io#3]
The current beginner BNBs are the best combos I'm aware of that don't use b2 loops or ws2,4.

This leads to there being 15 "bread and butters", since b+2,4,3 does more damage than b+2,f\~N f+4,1 but whiffs in some cases. Learning all these suboptimal routes instead of just learning to do f\~N ws2,4 is probably a bad idea. If the bnbs used ws2,4 there'd be less of them.

The other option is to just use f+4,1 for all of them.

It only takes at most 15 minutes in practice mode to figure out how f\~N ws2,4 works so I think it's probably okay to put them as beginner BNBs, but it's also only 2 damage which is not that significant.

**Comment by twaritwaikar** [comment]
ws24 should definitely be in the bnb list.
f41 should also be there for off axis cases.
b243 should also be there for the initial learning phases of learning combos.

I think it's best we list all the above and make sure the reader gets the idea that ws24 is the most preferred one and the one you should use unless you are off axis

**Comment by RogerDodger** [comment]
Think I resolved this by refocusing the BNBs. The concept of a "bread n butter" is to keep the memory burden low, e.g. this is the thing you do on everything for starters. So reducing variations as much as possible, rather than going for optimal easy combos, is the goal.

You move on from there to staples, which are combos tailored to a specific launcher (or category of launchers). These aim for optimal damage using consistent tech. They all have a variant without b2 loops, to be congruent with the advice in /b2-loops.

You (optionally) move on from there to extras, which are combos that are either inconsistent or very difficult.
