### ISSUE TITLE
Should we write b+2,f~N ws2,4 or b+2,f~N b~N,2,4

### ISSUE THREAD

**Issue by RogerDodger** [t7leeschool/t7leeschool.github.io#7]
Murakumo has typically used the latter. It's more precise and helpful for newer Lee players who don't necessarily know how to do ws moves after a mist step. However, it's harder to read, and the site already has a clear explanation on it for what the precise input is.

**Comment by RogerDodger** [comment]
(Although Marukumo has typically written it as b,N,2,4 I think b\~N,2,4 or maybe even b\~N\~2,4 would be more precise if we go with that option.)

**Comment by twaritwaikar** [comment]
@RogerDodger I find the latter less obvious to mean 'ws24 from a ms'. It may just complicate things for new ones who have already learned to do the ms ws motion from /faq.

The latter is exact, but we are not trying to cater to people who probably learned notations 2 days prior to reading the guide.

**Comment by RogerDodger** [comment]
Yeah, I think the aid in clarity for newbies is probably overstated as well. If you don't even know what b,N,2,4 is supposed to do, then it'd be pretty confusing.
